version: "3"

volumes:
  mysql-data:
    driver: local
  redis-data:
    driver: local

services:

  #--------------------------------------------------
  # Php API
  api:
    image: nginx:1.17.8
    ports:
      - "3000:80"
    volumes:
      - ./:/app
      - ./docker/nginx/app.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    image: hpf/php
    build: ./docker/php
    working_dir: /app
    volumes:
      - ./:/app
      - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    depends_on:
      - redis
      - mysql

  #--------------------------------------------------
  # Installer
  composer:
    image: composer:1.9.1
    working_dir: /app
    volumes:
      - ./:/app
    command: composer install

  #--------------------------------------------------
  # Cache
  redis:
    image: redis:4.0
    command: --appendonly yes
    ports:
      - "6379"
    volumes:
      - redis-data:/data

  #--------------------------------------------------
  # Database
  mysql:
    image: mariadb:10.4.11
    ports:
      - "3306"
    environment:
      MYSQL_DATABASE: api
      MYSQL_USER: api_user
      MYSQL_PASSWORD: api_pass
      MYSQL_ROOT_PASSWORD: api_root
    volumes:
      - mysql-data:/var/lib/mysql
